on: [push]

jobs:
  reviewer_required:
    name: Check if reviewer are required

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: Adzz/jest_test_action@v1.0.0
        with:
          command: build

      - name: 'Checking files'
        uses: ./
        with:
          files: '[ "./test" ]'
